### ISSUE TITLE
Extended token expiration option

### ISSUE THREAD

**Issue by jibon57** [shadowsocks/shadowsocks-hub-api#1]
Hello,

First of all thanks for your excellent work. I would like to request for an option to extended token expiration time or a way to renew token without password. Most of the application has an option like `remember me`. So, in this case if this application expire in 24 hours then other application will have conflict. 

Another request to share source code of `api.js` in good format. Not in this complied or uglify way so that other users can contribute too.

Thanks

**Comment by Eggham** [comment]
Hi,

Thanks for the very first request of this repo!

I'd prefer adding a `renew token` api to extending token expiration time for the sake of security. Perhaps a `logout` api is also needed...

Regarding the source code, I'd like to check in the source code, but unfortunately at the moment I am not permitted to do so (the code was written for work and I do not own it). I only get a permission to share the urglified version I have been trying to get permission but this is still an ongoing effort and the eventual outcome is uncertain...

**Comment by jibon57** [comment]
> I'd prefer adding a renew token api to extending token expiration time for the sake of security

Yes, at least it's important for general users. Basically they don't love to login again & again. For admin it can be for 24 hours.

> Perhaps a logout api is also needed...

It won't be difficult to add a logout I think.

> I'd like to check in the source code, but unfortunately..

I have expressed by expression only :) .. As you are sharing the project under an opensource project's banner so providing source code will be better too.

**Comment by Eggham** [comment]
Feature added.
