### ISSUE TITLE
500 Internal Server Error on get account request

### ISSUE THREAD

**Issue by soleimanim** [shadowsocks/shadowsocks-hub-api#2]
`{{base_url}}/api/account?id=348dd645-53ee-462a-85f6-936dc3ba4337`

I create Server, Node, Product and request an account and approve it, But when I try to get account details api returns 500 error with the following body

`{
    "error": {}
}`

**Comment by Eggham** [comment]
Thank you for your bug report!

The bug has been fixed. Please update and try again ;-)
