### ISSUE TITLE
Shadowsocks account not working

### ISSUE THREAD

**Issue by soleimanim** [shadowsocks/shadowsocks-hub-api#4]
Thank you for your fast bug fixes 👍

How can I connect to shadowsocks account ?

I can create and approve account, Then I get the account details include: Method, password, port and server IP address. But by using this information I can not connect to shadowsocks server.

For shadowsocks-restful-api I use the following command to start shadowsocks and integrate it with restful api.

But for this repository I don't know how to start shadowsocks to integrate it with your code.
`ss-manager -m aes-256-cfb -u --manager-address /tmp/shadowsocks-manager.sock --fast-open`

**Comment by Eggham** [comment]
After running shadowsocks-libev as you mentioned, you also have to run `shadowsocks-restful-api` as follows (please refer to the that repository for details):
```
cd ~/shadowsocks-restful-api
node app.js
```

Basically, you have to run `shadowsocks-hub-api`, `shadowsocks-restful-api`, and `shadowsocks-libev`.

You also have to make sure the `port` and `password` of the Node you created within `shadowsocks-hub-api` match those in `shadowsocks-restful-api`, which are specified in `.env`.
