### ISSUE TITLE
A route for user (not admin) to get their accounts

### ISSUE THREAD

**Issue by soleimanim** [shadowsocks/shadowsocks-hub-api#5]
A route is required for user to get a list of their accounts.

When I add a new `Account` I get an ID which is not for the created account. If I want to get the requested account details first I should call `account/all` by admin token then get my account ID, Then login again with normal user and request to get my account details.

`account/all` should also work for normal user but just returns accounts that are associated  with current user.

**Comment by Eggham** [comment]
Good point! A new route (getAccountsByUserId) has been added. Please refer to README.
