### ISSUE TITLE
no traffic update

### ISSUE THREAD

**Issue by rchen9012** [shadowsocks/shadowsocks-hub-api#6]
everything works but no traffic update to database table

**Comment by Eggham** [comment]
Could you please provide more details? 

You may also try shadowsocks-hub https://github.com/shadowsocks/shadowsocks-hub.git. It has web ui that can display traffic chart.

**Comment by rchen9012** [comment]
I use curl command to check out traffic stored in database.  It seem like shadowsocks-hub-api is not getting any traffic usage update from shadowsocks-rest-api.  Just checked shadowsocks-rest-api returned 500 error. 
<img width="1145" alt="9e2536ab-bce9-47fa-9a42-9d1b45a57c73" src="https://user-images.githubusercontent.com/387998/43942801-f68d8dfc-9cab-11e8-9469-8cd71337d2ed.png">

**Comment by Eggham** [comment]
fixed the shadowsocks-rest-api bug.

**Comment by rchen9012** [comment]
sorry for late reply.  I want to take more time to test the fix.  It's confirm working.  can you please explain when the traffic request is sent to shadowshocks-rest-api?  I noticed if not traffic, database will not get updated.  only update when traffic goes through vpn.  Also "lastmetterreading" is the same as "usage" if so why need both fields?

<img width="1440" alt="screen shot 2018-08-14 at 12 53 11 am" src="https://user-images.githubusercontent.com/387998/44045857-7993f9ea-9f5c-11e8-8475-45cd4ac33c75.png">

**Comment by Eggham** [comment]
Thanks for the confirmation. It's good to know it's working as expected.

Traffic request is sent to shadowsocks-rest-api periodically. But the database will be updated only if there is new traffic (preventing saving duplicate traffic data).

`lastmaterreading`is not always the same as the `usage`, bug very often they would be the same...
